apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
spec:
  selector:
    matchLabels:
      app: practice-deployment
  template:
    metadata:
      labels:
        app: practice-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
