apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-deployment
spec:
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        volumeMounts:
          - mountPath: /disk
            name: disk
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8085
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: lab4-pvc
          
