apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3
  template:
    metadata:
      labels:
        app: lab3
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.2-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"