apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab4-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
