apiVersion: v1
kind: Pod
metadata:
  name: practice-pod
  labels:
    name: practice-pod
spec:
  containers:
  - name: practice-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
